### ISSUE TITLE
kills Bootstrap 3 dropdowns

### ISSUE THREAD

**Issue by keks2k** [etbusch/web-developer-form-filler-ext#1]
When this plugin (version 1.0.16) is installed into Firefox (66.0.2), it kills Bootstrap 3 dropdowns.

Steps to reproduce:
- install/enable plugin
- visit https://getbootstrap.com/docs/3.4/javascript/#dropdowns
- see non-working dropdowns
- disable plugin
- enjoy working dropdowns

Reproducible under Windows and Linux (Ubuntu / KDE)

edit: Bootstrap 4 is not affected

**Comment by etbusch** [comment]
Hi @keks2k,
Thanks for the detailed issue report. I am able to reproduce it as well. 

I'll take a look at whats going on this evening. I imagine it could be a conflict with the internal Bootstrap 3 that this extension uses, but that is just speculation.

**Comment by etbusch** [comment]
I've fixed this issue, thanks again for the bug report!

**Comment by keks2k** [comment]
Hey, no problem, you are welcome! :-)

I guess there might have been a lot of people affected by this, so it's good to know it got fixed quickly.

To my mind, it shouldn't be that easy to kill bootstrap functionality so silently..
