### ISSUE TITLE
Icon has same color as Firefox interface

### ISSUE THREAD

**Issue by noehmeier** [etbusch/web-developer-form-filler-ext#11]
I use the actual "Firefox Browser Developer" 78.0b9 (64-Bit), the Developer Edition of Firefox. It starts with a dark theme and the interface of the Firefox menu is the same as the icon of the Web Developer Form Filler. So it looks like there is no icon-button. If you hover it, you see in a smilar color slightly the pencil.

Can u change the coler of the menu icon, so it has a good contrast in the Firefox dark themes?

**Comment by cweiske** [comment]
I have the same problem. I'm using Firefox Color to color my different Firefox profiles so I can distinguish them.
My work profile has a dark red background, and the form filler icon is not really visible now.

![2020-11-24](https://user-images.githubusercontent.com/59036/100069076-9a7f1c80-2e38-11eb-80dc-83c4de2192cb.png)

**Comment by etbusch** [comment]
I've added dark theme icons. A new version of the extension will be published shortly. Thanks for reporting this!

**Comment by cweiske** [comment]
New icon looks fine!
