### ISSUE TITLE
"TypeError: a is undefined" from mousetrap.min.js bundled into this extension

### ISSUE THREAD

**Issue by lpar** [etbusch/web-developer-form-filler-ext#15]
It's possible that this has been happening for a while, and I only just noticed because I switched Firefox's debugger to pause on any exception.

**Comment by etbusch** [comment]
Interesting! I am unable to reproduce this after fiddling around in the debugger for a few minutes. 

Did you take any specific action to cause the exception?

mousetrap powers the keyboard shortcut functionality of this extension (and it probably needs some love), so you may have some conflicts with other extensions listening for keyboard shortcuts.

**Comment by etbusch** [comment]
Please reopen this if you continue to see that error.
