### ISSUE TITLE
not work after new update

### ISSUE THREAD

**Issue by varta2014** [etbusch/web-developer-form-filler-ext#16]
hi,
extension not work in chrome or opera anymore with new update 
can fix soon please, thanks
regards

**Comment by etbusch** [comment]
Hi,

This version of the extension is only available in the Firefox add-on store, and isn't tested on Chrome or Opera. 

Are you referring to the version available on the Chrome Web Store? That code is hosted at the following link, and is mostly abandoned: https://github.com/abzubarev/web-developer-form-filler-ext

If you're manually installing this extension into Chrome or Opera, I can take a look into seeing if it works or not when I have a moment.

**Comment by varta2014** [comment]
hi, thanks for reply
yes i talk about chrome not work after update 9 May 2021 Version 1.0.13.1
please help thanks

**Comment by etbusch** [comment]
Ah, so you are referring to the other version of this extension before I forked it.. Please file an issue here: https://github.com/abzubarev/web-developer-form-filler-ext
