### ISSUE TITLE
No longer saving on most forms

### ISSUE THREAD

**Issue by MegaphoneJon** [etbusch/web-developer-form-filler-ext#21]
I'm having trouble saving on forms, including forms I've saved on before.  Here's the error from my Console:

```
Filler error: an input does not have id or name attribute. Skipping 4 content_script.js:10:13
    serializeForm moz-extension://f9ba0e33-7ed3-4806-9ddc-f4355de2c16f/javascripts/content_script.js:10
    jQuery 2
    serializeForm moz-extension://f9ba0e33-7ed3-4806-9ddc-f4355de2c16f/javascripts/content_script.js:5
    jQuery 2
    serializeForm moz-extension://f9ba0e33-7ed3-4806-9ddc-f4355de2c16f/javascripts/content_script.js:4
    <anonymous> moz-extension://f9ba0e33-7ed3-4806-9ddc-f4355de2c16f/javascripts/content_script.js:62
```

**Comment by etbusch** [comment]
This error message is emitted when the extension can't find a unique deterministic identifier for a given input field that it can then use to re-fill later on. If it is happening to the entire form, then there's something afoot.

Can you share an example of a form that this happens on? What browser/OS are you using?
