### ISSUE TITLE
No longer saving form (2)

### ISSUE THREAD

**Issue by wmclt** [etbusch/web-developer-form-filler-ext#22]
# Issue
Just like [MegaphoneJon](https://github.com/MegaphoneJon) [on 2 Sep 2021](https://github.com/etbusch/web-developer-form-filler-ext/issues/21#issue-987150548), I'm having issues saving forms.

Stack trace:
`
Filler error: an input does not have id or name attribute. Skipping [content_script.js:10:13](moz-extension://a30450eb-41be-4448-ae2b-0ed582a9674a/javascripts/content_script.js)
    serializeForm moz-extension://a30450eb-41be-4448-ae2b-0ed582a9674a/javascripts/content_script.js:10
    jQuery 2
        each
        each
    serializeForm moz-extension://a30450eb-41be-4448-ae2b-0ed582a9674a/javascripts/content_script.js:5
    jQuery 2
        each
        each
    serializeForm moz-extension://a30450eb-41be-4448-ae2b-0ed582a9674a/javascripts/content_script.js:4
    <anonymous> moz-extension://a30450eb-41be-4448-ae2b-0ed582a9674a/javascripts/content_script.js:62
`

# Info
Browser: Firefox 96.0 (64 bit)
OS: Kubuntu 21.04 
Host: Precision 7540
Kernel: 5.11.0-49-generic

Other Firefox extensions: Bitwarden, Leechblock 

# Reproduce: 
1. go to https://www.w3schools.com/html/tryit.asp?filename=tryhtml_form_submit
2. try to save form

**Comment by etbusch** [comment]
Hi, 

I tried to reproduce the error on that W3 Schools form sandbox page, and I don't believe this has ever worked for forms within iframes, which is how this page renders the test form.

The console error is complaining about a hidden textarea on the left side of the page, which should not be included in a form save IMO. 

Happy to look into other forms that aren't working!
