### ISSUE TITLE
"Clear sets" should ask for confirmation

### ISSUE THREAD

**Issue by cweiske** [etbusch/web-developer-form-filler-ext#23]
I wanted to import a json export and because the import button is only a "+" but the "clear sets" on the right is much bigger, I accidentially cleared all 5 form sets for the domain without actually wanting that.

It would be nice if there was a confirmation, or a "restore" button.

**Comment by cweiske** [comment]
Thanks!

**Comment by etbusch** [comment]
thank you for the suggestion!
