### ISSUE TITLE
Firefox clear cache clears all settings

### ISSUE THREAD

**Issue by jazzzsoftware** [etbusch/web-developer-form-filler-ext#5]
Is there any way to make the settings persistent?

This does not happen with the Chrome version.

Thanks for this.

**Comment by etbusch** [comment]
Hi @Surfrat,

Thanks for the bug report!

It looks like there is an API that is more well suited for storing sets and settings than the `window.localStorage` API, which in Firefox is cleared when you delete browsing data.

I'll look into migrating storage functions to `browser.storage` when I have some time this weekend.

**Comment by jazzzsoftware** [comment]
Thank you very much.

**Comment by jazzzsoftware** [comment]
Tested and work's 100%. Tested by using FF clear history and also tested with Ccleaner. Both used to delete all the sets. 

Thank you.
