### ISSUE TITLE
Support for frames in framesets

### ISSUE THREAD

**Issue by Deluvio** [etbusch/web-developer-form-filler-ext#7]
it seems that there is no support for frames in framesets. 
i'm using the FF add-on.

**Comment by etbusch** [comment]
Hi @Deluvio,

Thanks for the issue report. 

Are you referring to actual `<frame>` and `<frameset>` tags? 

These have been removed from the HTML5 spec, but if you have a use-case where support is needed I can look into implementing support.

**Comment by etbusch** [comment]
I don't think this is technically possible. Please reopen if you know otherwise.
